# Generated by Django 6.0.6 on 2026-06-08 19:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('visitor', 'Відвідувач'), ('concierge', 'Консьєрж'), ('admin', 'Адміністратор')], default='visitor', max_length=20, verbose_name='Роль користувача')),
                ('is_concierge', models.BooleanField(default=False, verbose_name='Консьєрж')),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='Адміністратор')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Останній вхід')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Вхід'), ('logout', 'Вихід'), ('register', 'Реєстрація'), ('update', 'Оновлення')], max_length=20, verbose_name='Тип активності')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('details', models.TextField(blank=True, verbose_name='Деталі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог активності',
                'verbose_name_plural': 'Логи активності',
                'ordering': ['-timestamp'],
            },
        ),
    ]
